# Generated by Django 3.2.6 on 2021-10-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(verbose_name='date posted')),
                ('age', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
